apiVersion: apps/v1
kind: Deployment
metadata:
  name: devtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devtest
  template:
    metadata:
      labels:
        app: devtest
    spec:
      containers:
      - name: devtest
        image: ghcr.io/schenna43lp1/devtest:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "250m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5